# Site settings
title: My GitHub Pages Site
description: A simple website hosted on GitHub Pages
baseurl: ""  # Leave empty if deploying to the root of the GitHub Pages site
url: "https://yourusername.github.io"  # Replace with your GitHub Pages URL

# Theme (choose a supported Jekyll theme)
theme: jekyll-theme-minimal  # You can change this to another GitHub Pages-supported theme

# Plugins (GitHub Pages supports a limited set of Jekyll plugins)
plugins:
  - jekyll-seo-tag  # Adds SEO tags
  - jekyll-sitemap  # Generates a sitemap.xml

# Navigation settings (if using a theme that supports navigation)
nav:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact

# Markdown settings
markdown: kramdown  # Default Markdown processor

# Other options
include:
  - _pages  # Include additional folders (optional)
exclude:
  - README.md  # Exclude files from being processed
  - Gemfile
  - Gemfile.lock

# GitHub Pages settings
github:
  is_project_page: false
